#!/bin/bash
BASE="$(cd "$(dirname "$0")" && pwd)"
echo "Creando estructura de directorios..."
mkdir -p "$BASE/logs"
mkdir -p "$BASE/reports"
mkdir -p "$BASE/memory"
mkdir -p "$BASE/state"
mkdir -p "$BASE/recovery"
mkdir -p "$BASE/agents/audit-agent"
mkdir -p "$BASE/agents/seo-agent"
mkdir -p "$BASE/agents/content-agent"
mkdir -p "$BASE/console"
touch "$BASE/logs/audit.log"
touch "$BASE/logs/seo.log"
touch "$BASE/logs/content.log"
echo "{\"status\":\"ready\"}" > "$BASE/state/current_task.json"
echo "OK — Estructura lista en: $BASE"
ls -la "$BASE"
